# Travis doesn't have a fortran build config, so we'll use c as a base and
# create our own environment
language: c

sudo: required

install:
    - sudo apt-get install gfortran automake

before_script:
    - ./configure && make

script: 
    - make check
